version: '2'
services:
    elasticsearch:
        image: elasticsearch:8.8.1
        volumes:
            - ./esdata:/usr/share/elasticsearch/data
    kibana:
        image: kibana:8.8.1
        ports:
            - "5601:5601"
        links:
            - elasticsearch
    screeps-stats:
        build: .
        links:
            - elasticsearch:elasticsearch
        entrypoint: wait-for-it/wait-for-it.sh -t 30 elasticsearch:9200 -- python screeps_etl/screepsstats.py
